-- The sequence of triangle numbers is generated by adding the natural numbers.
-- What is the value of the first triangle number to have over five hundred divisors?

import Numerix (factors)

-- sum n, n=0..inf = n * (n + 1) / 2
triangle n = n * (n + 1) `div` 2
triangles = map triangle [1..]

answer = head . dropWhile ((< 500).length.factors) $ triangles

main = putStrLn . show $ answer